# Generated by Django 3.1.7 on 2021-02-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audioclass',
            options={'verbose_name': 'Audio class', 'verbose_name_plural': 'Audio classes'},
        ),
        migrations.AlterModelOptions(
            name='audioclassweek',
            options={'verbose_name': 'Audio class week', 'verbose_name_plural': 'Audio class weeks'},
        ),
        migrations.AddField(
            model_name='audioclassweek',
            name='audio_file',
            field=models.FileField(default='', upload_to='audios'),
        ),
    ]
