# Generated by Django 3.1.7 on 2021-03-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0002_auto_20210223_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioclassweek',
            name='audio_file',
            field=models.FileField(blank=True, default='', null=True, upload_to='uploads/audios'),
        ),
    ]
